### ISSUE TITLE
Build function is not available in the root of the package

### ISSUE THREAD

**Issue by SSeanin** [abishekatp/stylers#59]
The package requires `build.rs` file to be present and in the `build.rs` file a `build` function in used and called from the root of `stylers` package which is not available in the root.

I've added the package as a dependency and also a build-dependency is there anything I'm missing?

**Comment by abishekatp** [comment]
Hi @SSeanin, If you are using trunk for building make sure you have added the `Trunk.toml` file with the following code snippet in your project root folder.
```
[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = ["-c", "cp ./target/main.css $TRUNK_STAGING_DIR/"]
```

Also make sure you have linked the output css file to you project. Usually we do that by adding `link` tag in the `index.html`

`<link rel="stylesheet" href="/main.css" />`


If you are still having some problems, Either refer to the [examples](https://github.com/abishekatp/stylers/tree/main/examples) section or push an example code on the github and share the link here.

**Comment by SSeanin** [comment]
Hi @abishekatp,

I've added the trunk hook and also linked the stylesheet. The error is rather a strange compile time error!
I'll push a commit and link it here.

Please take a look.
https://github.com/SSeanin/mecha-leptos/tree/development

**Comment by SSeanin** [comment]
Oh, and I'll attach a screenshot of the error just in case.

![image](https://github.com/abishekatp/stylers/assets/40974990/c8c458b7-e70b-4674-8e14-f756a84bfa04)

**Comment by abishekatp** [comment]
Can you please share the content of the `Cargo.toml` file? 
`If you can share your project template(only template) as a whole, it will be helpful to debug.`

**Comment by SSeanin** [comment]
Of course, here is my `Cargo.toml` content:

```
[package]
name = "mecha-leptos"
description = "Personal blog frontend using WASM and leptos"
version = "0.0.1"
edition = "2021"
authors = ["Saeed Andalib <saeedandalib5@gmail.com>"]
keywords = ["blog", "frontend", "leptos", "wasm"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "mecha"
path = "src/lib/lib.rs"

[dependencies]
leptos = { version = "0.6.3", features = ["csr", "nightly"] }
stylers = "0.3.2"

[build-dependencies]
stylers = "0.3.2"
```

**Comment by SSeanin** [comment]
Of course,

Here is the `Cargo.toml` content:

```toml
[package]
name = "mecha-leptos"
version = "0.0.1"
edition = "2021"
keywords = ["blog", "frontend", "leptos", "wasm"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "mecha"
path = "src/lib/lib.rs"

[dependencies]
leptos = { version = "0.6.3", features = ["csr", "nightly"] }
stylers = "0.3.2"

[build-dependencies]
stylers = "0.3.2"

```

**Comment by abishekatp** [comment]
> Hi @abishekatp,
> 
> I've added the trunk hook and also linked the stylesheet. The error is rather a strange compile time error! I'll push a commit and link it here.
> 
> Please take a look. https://github.com/SSeanin/mecha-leptos/tree/development

Sorry I didn't see this message. I will check and let you know. But it might take some time.

**Comment by cBournhonesque** [comment]
I have the same error; which is preventing me from trying out the library

**Comment by ChristophSonnleitner** [comment]
I am facing the same issue

**Comment by gembleman** [comment]
I was having the exact same problem.
However, I solved it with a feature built into Trunk.
Just add 
```
<link data-trunk rel="css" href="./style.css" /> 
```
to the <head> part of your index.html and place the css file in your working folder.
It's a stopgap, but it worked for me.

**Comment by SSeanin** [comment]
@gembleman I tried the solution and added the data-trunk link asset to index.html, this did not fix the problem.
Can you share a template or the exact steps of how you managed to fix it?

**Comment by gembleman** [comment]
@SSeanin A small example of driving a Leptos CSR with CSS into Trunk.

https://github.com/gembleman/css_in_trunk

After all, the point is that you want to apply CSS to Leptos while using Trunk, right?
That's how I understood your question, and that's why I wrote this method.
I'm not very good at English, so I apologize if it's not what you wanted.

**Comment by SSeanin** [comment]
@gembleman Oh I see.
You're right about the point being applying CSS in Leptos applications.
However, most modern frontend technologies seem to provide a way of allowing for a modular and maintainable CSS structure(i.e. not having to worry about clashing class names between components), see for example [Adding a CSS Modules Stylesheet](https://create-react-app.dev/docs/adding-a-css-modules-stylesheet).
This problem along with actually parsing the CSS and SASS/SCSS are what most of the styling crates aim to solve for Leptos.

**Comment by 143mailliw** [comment]
@SSeanin I've figured out the problem.

```toml
[dependencies]
leptos = { version = "0.6.3", features = ["csr", "nightly"] }
stylers = "0.3.2"

[build-dependencies]
stylers = "0.3.2"
```

must actually be

```toml
[dependencies]
leptos = { version = "0.6.3", features = ["csr", "nightly"] }
stylers = "1.0.0-alpha"

[build-dependencies]
stylers = "1.0.0-alpha"
```

Following the installation gude (which says to use `stylers = {version = "*"}`) or using `cargo add` does not work because 1.0.0-alpha is an alpha version. You must specify that you want `1.0.0-alpha`.
